feat: type definitions, es modules usage
cometd/cometd-nodejs-client pull request #25
Opened 2020-08-25 14:24 UTC by t-richards

This PR:

1. Adds a set of TypeScript type definitions (`.d.ts`) to the library.
2. Adds example code to the readme for using the library via ES modules.

### Testing

How I tested these type definitions locally:

1. Convert all `test/` files from `.js` -> `.ts`
2. Add `@types/node`, `@types/mocha`, `ts-node` packages
3. Convert all top-level variables in tests from `const` -> `let`
4. `mocha -r ts-node/register test/*.ts`
5. Expect tests to pass!

2020-08-25 14:45 UTC, sbordet commented
@t-richards thanks for the PR, but I would like you to open an issue first to discuss what is the problem first and what's the best way to solve it.

I don't see what the problem is right now?
We don't use TS and I don't see why we should?
I am genuinely asking, thanks.

2020-08-25 15:07 UTC, t-richards commented
To be clear, I'm not suggesting this library should directly use TypeScript. 😄 

The motivation behind this PR is for users of this library who are using TypeScript in their own project. Here's the issue:

Let's say I have the following TypeScript code:

```typescript
// File: src/main.ts

import { CometD } from 'cometd';
import { adapt } from 'cometd-nodejs-client';
adapt();

const client = new CometD();
```

And the following TypeScript configuration:

```json
// File: tsconfig.json
{
    "include": [
        "src/**/*"
    ],
    "compilerOptions": {
        "target": "es2017",
        "module": "commonjs",
        "baseUrl": "./src",
        "noEmit": true,
        "strict": true,
        "noImplicitAny": true,
        "esModuleInterop": true
    }
}
```

Given the above two things, attempting to call the `adapt()` function from this library results in a build error.

```sh-session
> tsc

src/main.ts:4:23 - error TS7016: Could not find a declaration file for module 'cometd-nodejs-client'. '/node_modules/cometd-nodejs-client/cometd-nodejs-client.js' implicitly has an 'any' type.
  Try `npm install @types/cometd-nodejs-client` if it exists or add a new declaration (.d.ts) file containing `declare module 'cometd-nodejs-client';`

4 import { adapt } from 'cometd-nodejs-client';
                        ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

As the project owner, I have a few options at this point:

 1. Throw away my "strict" and "noImplicitAny" flags, allowing undefined values to sneak their way through my code
 2. Write a `.d.ts` file for this library and include it my project alone, never to be reused
 3. Write a `.d.ts` file for this library and submit it upstream to the project itself
 4. Write a `.d.ts` file for this library and submit it to the `DefinitelyTyped` types monorepo

This PR is a manifestation of option number 3. It would allow downstream consumers of this library (e.g. me!) to use a strict TypeScript configuration in their projects without having to author their own type definitions, as these definitions would be provided by the library itself.

😄  Hope this answers your question!

2020-08-25 15:11 UTC, sbordet commented
@t-richards yes please open an issue with your comment and let's continue the discussion there.

2020-08-27 08:15 UTC, sbordet requested changes

2020-08-27 08:15 UTC, sbordet commented on cometd-nodejs-client.d.ts
> +export interface Proxy {
Can you please add the license boilerplate at the beginning of the file - copy it from `cometd-nodejs-client.js`.

2020-08-27 08:15 UTC, sbordet commented on cometd-nodejs-client.d.ts
> +export interface Proxy {
Is it possible to rename this to `HttpProxy`?

2020-08-27 08:18 UTC, sbordet commented
@t-richards, since you've done it, would you contribute also (maybe another PR) at least one test (converted or new) in TS?

Can tests be run by `mocha` in "mixed" mode, i.e. some of them in TS and some in JS?

2020-09-04 18:40 UTC, t-richards commented
@sbordet I believe that `mocha` can run mixed TypeScript / JavaScript tests.

That said, if the test conversion process from JS -> TS is somewhat straightforward, I think it might make sense to convert them all in one go and not bother with the mixed mode. I will try this out in a separate PR.

2020-12-22 10:44 UTC, merged